// <auto-generated />
using System;
using FCHCaracteriza.Core.Core.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FCHCaracteriza.Core.Migrations
{
    [DbContext(typeof(FCH_PLATPROVEE_MINERIAContext))]
    partial class FCH_PLATPROVEE_MINERIAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FCHCaracteriza.Core.Core.Domain.TabContacto", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("numeric(18, 0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ambito")
                        .HasColumnName("ambito")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("Apellidos")
                        .HasColumnName("apellidos")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Cargo")
                        .HasColumnName("cargo")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Celular")
                        .HasColumnName("celular")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CodUsuario")
                        .HasColumnName("cod_usuario")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FecIng")
                        .HasColumnName("fec_ing")
                        .HasColumnType("datetime");

                    b.Property<string>("Fono")
                        .HasColumnName("fono")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Mail")
                        .HasColumnName("mail")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Nombres")
                        .HasColumnName("nombres")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnName("origen")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("RutContacto")
                        .IsRequired()
                        .HasColumnName("rut_contacto")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("RutEmp")
                        .IsRequired()
                        .HasColumnName("rut_emp")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("TipoContacto")
                        .HasColumnName("tipo_contacto")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoEmpresa")
                        .HasColumnName("tipo_empresa")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("TAB_CONTACTO");
                });

            modelBuilder.Entity("FCHCaracteriza.Core.Core.Domain.TabEmpresa", b =>
                {
                    b.Property<string>("RutEmp")
                        .HasColumnName("rut_emp")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Ambito")
                        .HasColumnName("ambito")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("Archivo")
                        .HasColumnName("archivo")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("ArchivoOri")
                        .HasColumnName("archivo_ori")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("CapacidadDoc")
                        .HasColumnName("capacidad_doc")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CapacidadMag")
                        .HasColumnName("capacidad_mag")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CapacidadPro")
                        .HasColumnName("capacidad_pro")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CapacidadTec")
                        .HasColumnName("capacidad_tec")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Ciudad")
                        .HasColumnName("ciudad")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Cluster")
                        .HasColumnName("cluster")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CodUsuario")
                        .HasColumnName("cod_usuario")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Correo")
                        .HasColumnName("correo")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DescArchivo")
                        .HasColumnName("desc_archivo")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("DescripRecom")
                        .HasColumnName("descrip_recom")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("DescripVinculacion")
                        .HasColumnName("descrip_vinculacion")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("DescripcionEmpresa")
                        .HasColumnName("descripcion_empresa")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Direccion")
                        .HasColumnName("direccion")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<short?>("Dotacion")
                        .HasColumnName("dotacion");

                    b.Property<string>("Especialidad")
                        .HasColumnName("especialidad")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FecIng")
                        .HasColumnName("fec_ing")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FecIniAct")
                        .HasColumnName("fec_ini_act")
                        .HasColumnType("datetime");

                    b.Property<string>("Fono")
                        .HasColumnName("fono")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("LinkBrechas")
                        .HasColumnName("link_brechas")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Origen")
                        .HasColumnName("origen")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Otro")
                        .HasColumnName("otro")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Pais")
                        .HasColumnName("pais")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("RazonSocial")
                        .HasColumnName("razon_social")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Recomendada")
                        .HasColumnName("recomendada")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Region")
                        .HasColumnName("region")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("RutUsuario")
                        .HasColumnName("rut_usuario")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("SitioWeb")
                        .HasColumnName("sitio_web")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("TipoEje")
                        .HasColumnName("tipo_eje")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoEmpresa")
                        .IsRequired()
                        .HasColumnName("tipo_empresa")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("TipoInfra")
                        .HasColumnName("tipo_infra")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("Venta")
                        .HasColumnName("venta");

                    b.Property<string>("Vinculaciones")
                        .HasColumnName("vinculaciones")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("RutEmp")
                        .HasName("PK_TAB_EMPRESA_1");

                    b.ToTable("TAB_EMPRESA");
                });

            modelBuilder.Entity("FCHCaracteriza.Core.Core.Domain.TabSolTec", b =>
                {
                    b.Property<string>("CodSol")
                        .HasColumnName("cod_sol")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Ambito")
                        .HasColumnName("ambito")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("Beneficio")
                        .HasColumnName("beneficio")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("CapHum")
                        .HasColumnName("cap_hum")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("CodResp")
                        .HasColumnName("cod_resp")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("CodUsuario")
                        .HasColumnName("cod_usuario")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Descrip")
                        .HasColumnName("descrip")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("ElementoDife")
                        .HasColumnName("elemento_dife")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("Escalable")
                        .HasColumnName("escalable")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FecIng")
                        .HasColumnName("fec_ing")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FecInicio")
                        .HasColumnName("fec_inicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FecTermino")
                        .HasColumnName("fec_termino")
                        .HasColumnType("datetime");

                    b.Property<string>("Innovacion")
                        .HasColumnName("innovacion")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Kpi")
                        .HasColumnName("kpi")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("Lugar")
                        .HasColumnName("lugar")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("LugarComp")
                        .HasColumnName("lugar_comp")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("ModeloNeg")
                        .HasColumnName("modelo_neg")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasMaxLength(1500)
                        .IsUnicode(false);

                    b.Property<string>("Nucleo")
                        .HasColumnName("nucleo")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("OtraAplic")
                        .HasColumnName("otra_aplic")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("Pais")
                        .HasColumnName("pais")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Patentado")
                        .HasColumnName("patentado")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PptaValor")
                        .HasColumnName("ppta_valor")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("PrincipalesComp")
                        .HasColumnName("principales_comp")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("PropiedadIntel")
                        .HasColumnName("propiedad_intel")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("RecomendTecn")
                        .HasColumnName("recomend_tecn")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("Recomendaciones")
                        .HasColumnName("recomendaciones")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("Replicable")
                        .HasColumnName("replicable")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Resolucion")
                        .HasColumnName("resolucion")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.Property<string>("RutEmp")
                        .IsRequired()
                        .HasColumnName("rut_emp")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("RutUsuario")
                        .IsRequired()
                        .HasColumnName("rut_usuario")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("SolucSimil")
                        .HasColumnName("soluc_simil")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TecnAlternativa")
                        .HasColumnName("tecn_alternativa")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("TendenciaTecnologica")
                        .HasColumnName("tendencia_tecnologica")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("TipoCadVal")
                        .HasColumnName("tipo_cad_val")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoEspec")
                        .HasColumnName("tipo_espec")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("TipoFoco")
                        .HasColumnName("tipo_foco")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoMadurez")
                        .HasColumnName("tipo_madurez")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoModeloNeg")
                        .HasColumnName("tipo_modelo_neg")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoOrigen")
                        .HasColumnName("tipo_origen")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TipoProceso")
                        .HasColumnName("tipo_proceso")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CodSol")
                        .HasName("PK_SOL_TEC");

                    b.ToTable("TAB_SOL_TEC");
                });
#pragma warning restore 612, 618
        }
    }
}
